---
title: "25->20 mph streets"
author: "Patrick Spauster"
date: "6/2/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(RSocrata)
library(sf)
library(leaflet)
library(htmltools)

```

```{r}

speed_limits <- read.socrata("https://data.cityofnewyork.us/resource/r6fm-v9ag.csv") %>% 
  st_as_sf(wkt = "the_geom")

crash_data <- read.socrata("https://data.cityofnewyork.us/resource/h9gi-nx95.csv?$where=crash_date > '2018-12-31T00:00:00.000'")

crash_data_sf <- crash_data %>% 
  filter(!is.na(latitude)) %>% 
  st_as_sf(coords = c("longitude", "latitude"))

boroughs <- read.socrata("https://data.cityofnewyork.us/resource/7t3b-ywvw.csv")%>% 
  st_as_sf(wkt = "the_geom")

counties <- c("005", "047", "061", "081", "085")

boroughs <- tigris::counties(state = "NY", cb = TRUE) %>% 
  filter(COUNTYFP %in% counties) %>% 
  mutate(boro_name = case_when(
    NAME == "New York" ~ "Manhattan",
    NAME == "Richmond" ~ "Staten Island",
    NAME == "Kings" ~ "Brooklyn",
    T ~ NAME
  )) %>% 
  st_set_crs(st_crs(crash_data_sf))

#use this to backfill borough for the 200k missing borough
crash_data_missing_boro <- crash_data_sf %>%
  filter(borough == "" | is.na(borough)) %>% 
  st_join(boroughs, left = T) %>% 
  mutate(borough_fill = toupper(boro_name)) %>% 
  as.data.frame()



```


Group by borough to eliminate duplicate street names
```{r}

speed_limits_borough <- st_intersection(speed_limits, boroughs)

streets_speeds <- speed_limits_borough %>%
  mutate(street = if_else(street == "DE KALB AVENUE", "DEKALB AVENUE", street)) %>% 
  group_by(boro_name, street) %>% 
  summarize(min_speed = min(postvz_sl, na.rm = T),
            max_speed = min(postvz_sl, na.rm = T),
            length_25 = sum(shape_leng[postvz_sl == 25], na.rm = T),
            length_total = sum(shape_leng, na.rm = T),
            geometry = st_union(the_geom)) %>% 
  mutate(prop_25 = length_25/length_total,
         borough = toupper(boro_name))


```

Match to the street data 
```{r}

crash_data_clean <- crash_data %>%
  mutate(number = str_extract(cross_street_name, "\\b\\d+(?:-\\d+)?\\b"),
         alt_street = trimws(str_replace(cross_street_name, "\\b\\d+(?:-\\d+)?\\s*(?=\\D)", "")),
         on_street_name = trimws(if_else(on_street_name=="", alt_street, on_street_name))) %>% 
  left_join(crash_data_missing_boro %>% select(collision_id, borough_fill), by = "collision_id") %>% 
  mutate(borough = if_else(borough == "", borough_fill, borough),
         on_street_name = case_when(
           str_detect(on_street_name, "EXPY|EXPWY") ~ str_replace_all(on_street_name, "EXPY|EXPWY", "EXPRESSWAY"),
           str_detect(on_street_name, "PKWY") ~ str_replace_all(on_street_name, "PKWY", "PARKWAY"),
           str_detect(on_street_name, "SAINT") ~ str_replace_all(on_street_name, "SAINT", "ST"),
           str_detect(on_street_name, " BRIDGE| RAMP") ~ str_replace_all(on_street_name, " BRIDGE| RAMP", ""),
           T~toupper(on_street_name)
         ))
  

crashes_streets_speed <- streets_speeds %>% 
  left_join(crash_data_clean, by = c("borough" = "borough", "street" = "on_street_name"))

misses <- anti_join(crash_data_clean, streets_speeds, by = c("borough" = "borough", "on_street_name" = "street")) %>% 
  filter(!(is.na(longitude) & is.na(borough)),!((is.na(borough)&latitude==0)))

#check the integrity of this join
```


```{r}
street_sum <- crashes_streets_speed %>% 
  #as.data.frame() %>% 
  group_by(borough, street) %>% 
  summarize(prop_25 = first(prop_25),
            total_crashes = n(),
            length_total = first(length_total),
            unsafe_speed_crashes = sum(
              contributing_factor_vehicle_1 == "Unsafe Speed" | contributing_factor_vehicle_2 == "Unsafe Speed",
              na.rm = T)
            ) %>% 
  mutate(crash_pmile = total_crashes/length_total,
         speedcrash_pmile = unsafe_speed_crashes/length_total)

```

```{r}

top50 <- street_sum %>%
  filter(prop_25 >= 0.7, total_crashes >=35, length_total >= 250) %>% 
  arrange(desc(speedcrash_pmile)) %>% 
  head(50)

write_csv(top50, url = "top50_speedcrashpmile.csv")

top50raw <- street_sum %>%
  filter(prop_25 >= 0.7, total_crashes >=35, length_total >= 250) %>% 
  arrange(desc(unsafe_speed_crashes)) %>% 
  head(50)

#%>% 
 # left_join(speed_limits_borough %>% select(boro_name, street, the_geom), by = c("borough" = "boro_name", ))


```


```{r}

top50_map <- leaflet(top50) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addPolylines(color = "red", opacity = 0.7,
               popup = ~paste0(street,
                               "<br><b>Since 2019</b><br>",
                               total_crashes, " total collisions <br>",
                               unsafe_speed_crashes, " collisions caused by unsafe speed"),
               group = "Most speeding collisions per mile") %>% 
  addPolylines(data = top50raw, color = "red", opacity = 0.7,
               popup = ~paste0(street,
                               "<br><b>Since January 2019</b><br>",
                               total_crashes, " total collisions <br>",
                               unsafe_speed_crashes, " collisions caused by unsafe speed"),
               group = "Most total speeding collisions") %>% 
  addLayersControl(baseGroups = c("Most speeding collisions per mile", "Most total speeding collisions"),
                  options = layersControlOptions(collapsed = F))

top50_map

mapview::mapshot(top50_map, url = "map.html", file = "top50.png")

```

